server:
  port: ${PORT:8081}
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/auth_db}
  
  security:
    filter:
      order: 10

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    org.springframework.security: DEBUG
    com.tuempresa.authservice: DEBUG
