name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Auth Service
        run: |
          cd auth-service
          mvn -B package --file pom.xml -DskipTests
          
      - name: Build Frontend Service
        run: |
          cd frontend-service
          mvn -B package --file pom.xml -DskipTests
        
      - name: Create deployment directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir -p /home/${{ secrets.USERNAME }}/desk-mini
            mkdir -p /home/${{ secrets.USERNAME }}/desk-mini/config

      - name: Deploy JAR files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            auth-service/target/*.jar
            frontend-service/target/*.jar
            .env.prod
          target: "/home/${{ secrets.USERNAME }}/desk-mini"
          strip_components: 2

      - name: Start Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/desk-mini
            cp .env.prod .env
            
            # Detener servicios existentes
            pkill -f auth-service || true
            pkill -f frontend-service || true
            
            # Iniciar servicios
            nohup java -jar auth-service*.jar > auth.log 2>&1 &
            nohup java -jar frontend-service*.jar > frontend.log 2>&1 & 